openapi: 3.1.2
info:
  title: API Specification registry
  version: 1.0.0
  summary: Enturs central registry of OpenAPI specifications
  description: Enturs central registry of OpenAPI specifications
  contact:
    name: API Support
    url: https://entur.no
    email: support@entur.no
  x-entur-metadata:
    id: gha-api
    owner: team-api
    audience: internal
tags:
- name: API specifications
servers:
- url: https://api.entur.io/api-spec-registry
  description: Production
components:
  securitySchemes:
    jwt:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    SpecMetadata:
      type: object
      properties:
        repository:
          type: string
          examples:
          - api-spec-registry
      examples:
      - repository: api-spec-registry
    Spec:
      type: object
      properties:
        id:
          type: string
          examples:
          - api-spec-registry
      examples:
      - id: api-spec-registry
paths:
  "/specs":
    put:
      tags:
      - API specifications
      security:
      - jwt: []
      summary: Upload specification
      description: Upload a specification to the registry.
      operationId: uploadSpec
      parameters:
      - name: dryRun
        in: query
        description: If true, the specification will not be stored, but all the validation
          logic will be performed.
        schema:
          type: boolean
          default: false
      requestBody:
        description: Specification with metadata
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                spec: {}
                metadata:
                  "$ref": "#/components/schemas/SpecMetadata"
      responses:
        '201':
          description: Uploaded specification contained changes from the current version
        '204':
          description: Uploaded specification was identical to the current version
        '400':
          description: Uploaded specification was invalid
          content:
            application/problem+json:
              schema:
                "$ref": "components.yaml#/schemas/ProblemDetail"
      x-entur-permissions:
        value: api-spec-registry.api-specs:opprett
    get:
      tags:
      - API specifications
      summary: Get specifications
      description: Get all specifications stored in the registry.
      operationId: getSpecs
      parameters:
      - name: maxVersionsPerSpec
        in: query
        description: How many of the newest versions to fetch for each spec
        schema:
          type: integer
          minimum: 0
          default: 5
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/Spec"
  "/specs/{specId}":
    delete:
      tags:
      - API specifications
      security:
      - jwt: []
      summary: Delete specification
      description: Delete a specification from the registry.
      operationId: deleteSpec
      parameters:
      - name: specId
        in: path
        required: true
        description: The ID of the specification to delete.
        schema:
          type: string
      responses:
        '204':
          description: Specification deleted successfully
        '404':
          description: Specification not found
          content:
            application/problem+json:
              schema:
                "$ref": "components.yaml#/schemas/ProblemDetail"
      x-entur-permissions:
        value: api-spec-registry.api-specs:slett
