openapi: "3.1.0"
info:
  title: "Demo API"
  description: "This is a demo API specification."
  version: "1.0.0"
  contact:
    name: "Support"
    email: "support@example.com"
servers:
  - url: "http://example.com"
tags:
  - name: example
    description: "Tag for example operations"
paths:
  /example:
    get:
      description: "a good description"
      tags:
        - example
      operationId: getExample
      responses:
        "201":
          description: "OK"
          content:
            application/text:
              schema:
                type: object