openapi: "3.1.0"
info:
  title: ""
  description: "This is a demo API specification."
  version: ""
  contact:
    name: "Support"
    email: "support@example.com"
servers:
  - url: "http://example.com"
tags:
  - name: example
    description: "Tag for example operations"
paths:
  /example-api:
    trace:
      description: "a good description"
      tags:
        - example
      operationId: getExample
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: object