name: create release
on:
  push:
    branches:
      - main
permissions:
  pull-requests: write
  contents: write
  issues: write
jobs:
  release:
    uses: entur/gha-meta/.github/workflows/release.yml@v1
  update-lint-doc:
    needs: release
    uses: entur/gha-meta/.github/workflows/auto-doc.yml@v1
    with:
      workflow_file: .github/workflows/lint.yml
      readme_file: README-lint.md

  update-publish-doc:
    needs: release
    uses: entur/gha-meta/.github/workflows/auto-doc.yml@v1
    with:
      workflow_file: .github/workflows/publish.yml
      readme_file: README-publish.md
