name: create release
on:
  push:
    branches:
      - main
permissions:
  pull-requests: write
  contents: write
  issues: write
  actions: read
  id-token: write
jobs:
  test-validate-file:
    uses: ./.github/workflows/validate.yml
    with:
      path: fixture/openapi-good.json
  release:
    uses: entur/gha-meta/.github/workflows/release.yml@v1
  update-docs:
    needs: release
    if: needs.release.outputs.releases_created == 'false'
    strategy:
      max-parallel: 1 # Can't have them commit in parallel
      matrix:
        files:
          - workflow: .github/workflows/lint.yml
            readme: README-lint.md
          - workflow: .github/workflows/validate.yml
            readme: README-validate.md
          - workflow: .github/workflows/publish.yml
            readme: README-publish.md
    uses: entur/gha-meta/.github/workflows/auto-doc.yml@v1
    with:
      commit_default_author: 'github_actions'
      target_branch: 'release-please--branches--main'
      workflow_file: ${{ matrix.files.workflow }}
      readme_file: ${{ matrix.files.readme }}
