name: Setup spectral

description: Downloads and installs spectral


runs:
  using: composite
  steps:
    # Restore from cache if available
    - name: Restore cache
      id: restore-cache
      uses: actions/cache/restore@v6
      with:
        path: |
          ~/.local/bin/spectral
        key: spectral-cli-bin_v1.2.0_linux-x64

    # Download spectral-cli binary if not cached
    - name: Setup spectral-cli
      if: steps.restore-cache.outputs.cache-hit != 'true'
      env:
        GH_TOKEN: ${{ github.token }}
        SPECTRAL_CLI_BIN_VERSION: v1.2.0
        SPECTRAL_CLI_BIN_CHECKSUM: 20e0ab632c7af03fcdc5b6bde2339ed88b728f0049bfabb86e2e4a464bda2b5f
      shell: bash
      run: |
        # Print every statement if debugging
        [ -n "${{ runner.debug }}" ] && set -x

        asset_name="spectral-cli-bin_${SPECTRAL_CLI_BIN_VERSION}_linux-x64"
        filename="$HOME/.local/bin/spectral"

        mkdir -p "$HOME/.local/bin"
        gh release download -R entur/spectral-cli-bin ${SPECTRAL_CLI_BIN_VERSION} -p ${asset_name} -O ${filename}
        if ! (echo "$SPECTRAL_CLI_BIN_CHECKSUM $filename" | sha256sum --check --status); then
          echo "Checksum mismatch for ${filename}:"
          echo "  Expected: $SPECTRAL_CLI_BIN_CHECKSUM"
          echo "  Actual: $(sha256sum $filename)"
          exit 1
        fi

        chmod +x $filename
        echo "$HOME/.local/bin" >> $GITHUB_PATH

        echo "Installed spectral $(spectral --version)"

    - name: Save cache
      if: steps.restore-cache.outputs.cache-hit != 'true'
      uses: actions/cache/save@v6
      with:
        path: |
          ~/.local/bin/spectral
        key: ${{ steps.restore-cache.outputs.cache-primary-key }}
